import Head from 'next/head'
import Navbar from '../../components/navbar/NavBar'
import styles from '../../styles/Home.module.css'

/**
 * Display state of game (current stock value, company player info etc.)
 * Currently is under construction
 * @returns
 */
export default function State() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Admin App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className={styles.main}>
        State display!
      </main>
    </div>
  )
}
