import Head from 'next/head'
import { useEffect, useState } from 'react'
import { getCompanies, getSellers } from '../../api/database'
import Navbar from '../../components/navbar/NavBar'
import PlayerInformation from '../../components/stockmarket/PlayerInformation'
import SellerInformation from '../../components/stockmarket/SellerInformation'
import styles from '../../styles/Home.module.css'

/**
 * Display state of game (current stock value, company player info etc.)
 * Currently is under construction
 * @returns
 */
export default function State() {
  const [sellersInformation, setSellersInformation] = useState<any>({})
  const [sharersDisplay, setSharersDisplay] = useState<any[]>([])
  const [allCompanies, setAllCompanies] = useState<any[]>([])

  useEffect(() => {
  }, [])

  setTimeout(() => {
    getCompanies().then(companies => {
      setAllCompanies(companies)
      getSellers().then(newSellers => {
        setSellersInformation(newSellers)
      })
    })
  }, 1000)

  useEffect(() => {
    if (Object.keys(sellersInformation).length === 0) return;
    const sellers = sellersInformation.sellers;
    const shareBundles = sellersInformation.shareBundles;
    const newDisplay = []
    for (const seller of sellers) {
      newDisplay.push(<SellerInformation key={seller.id} bundles={shareBundles} seller={seller} companies={allCompanies} />)
    }
    setSharersDisplay(newDisplay)
  }, [sellersInformation])

  return (
    <div className={styles.container}>
      <Head>
        <title>Admin App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main>
        <div style={{ display: "flex", height: "100%" }}>
          <div style={{ position: "fixed" }}>
            <PlayerInformation />
          </div>
          <div style={{ marginLeft: "50%" }}>
            {sharersDisplay}
          </div>
        </div>
      </main>
    </div>
  )
}
