import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { playShow, pauseShow } from '../api/showManagement'
import { restartDatabase } from '../api/database'
import Navbar from '../components/navbar/NavBar'

/**
 * Admin page -> allows user to play / pause show and restart database to initial values
 * WARNING: currently it doesn't restart to initial but to default extracted from .json
 * There should be two buttons -> a restart and a reset
 * @returns admin page object
 */
export default function Admin() {
  const [playing, isPlaying] = useState(false) //stores if show is currently playing
  const [warningOn, setWarningOn] = useState(false) //stores if restart database warning shoud be displayed
  const warning = "YOU TRIED RESETTING THE DATABASE WHEN SHOW WAS PLAYING! PAUSE SHOW AND TRY AGAIN" //warning to be displayed when user attempts to restart database while show is playing

  return (
    <div className={styles.container}>
      <Head>
        <title>Admin App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        Show status: {playing ? `Show is playing` : `Show is not playing`}
        <button onClick={() => { playShow(isPlaying); setWarningOn(false); }}>Play Show</button>
        <button onClick={() => { pauseShow(isPlaying); setWarningOn(false); }}>Pause Show</button>
        <div>
          {warningOn ? `${warning}` : ''}
        </div>
        <div>
          <button onClick={() => { restartDatabase(setWarningOn) }}>Restart Database</button>
        </div>
      </main>
    </div>
  )
}
