import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function State() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Admin App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        State display!
      </main>
    </div>
  )
}
